### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by HarriBuh** [kl3jvi/sysinfo_app#10]
Google Pixel 7
Android 13
Rooted with Magisk 26.1

**Comment by kl3jvi** [comment]
Let me have a look @HarriBuh

**Comment by kl3jvi** [comment]
@HarriBuh Check out new release

**Comment by HarriBuh** [comment]
@kl3jvi Sorry for my absence, I haven't had the time to send you the logs you wanted. But I will try our your latest release.

Edit:
![markup_1000001377](https://github.com/kl3jvi/sysinfo_app/assets/123186113/2ee732e5-a2f6-4bda-9ff9-489483fba04a)
I never had this issue with any apps before, so I'm genuinely confused.
I tried both the arm64-v8 and the universal release. Fresh and clean install.

**Comment by kl3jvi** [comment]
Remove the current one, I probably forgot to upgrade the version code

**Comment by kl3jvi** [comment]
Closing as it's not occuring anymore
