### ISSUE TITLE
Minor discrepancies

### ISSUE THREAD

**Issue by IzzySoft** [kl3jvi/sysinfo_app#2]
Just wondering:

* [`LICENSE` file](https://github.com/kl3jvi/sysinfo_app/blob/main/LICENSE) says MIT, while the Readme states GPLv3 – which license applies?
* the APK at tag v1.0.2 identifies as v1.0.1 – is the tag name wrong, or the APK?
* Readme states "Until this very day the app does not require any permission to run on the Android Device." – yet the app requests location and Internet. It also seems to depend on Google Services, so it's not clear if it would run on a "de-googled" device (e.g. one with plain LineageOS with no GApps).

Thanks in advance for clarification!

**Comment by kl3jvi** [comment]
Thanks for catching these errors. I have made the changes to Readme File. As for trying a degoogled OS, the app might or might not work. I am really sorry I dont have a custom rom installed to try it out. Thanks a lot.

**Comment by IzzySoft** [comment]
Thanks for your quick response and action!

* MIT is set [on my end](https://apt.izzysoft.de/fdroid/index/apk/com.kl3jvi.sysinfo) then, too.
* what about the app version? Is it 1.0.1 or 1.0.2?
* thanks for updating the permission statement in the Readme!
* as for the de-googled device: I was hoping that maybe GMS could be dropped, to remove the non-foss taint from a nice app like this :smile:

Concerning above link: if you wish to link there, be welcome to use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it). Updates will become available there within 24h of your creating a new release and attaching an APK to it – and folks can use any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) to be notified of updates. Thanks for making your app available freely (and fossly)!
