### ISSUE TITLE
Getting System and Device Information

### ISSUE THREAD

**Issue by surajk16** [kl3jvi/sysinfo_app#8]
Hi. Thank you so much for making this open-source. I am trying to build a similar app and it has really been helpful. I was looking at how you get the system and device information and couldn't find anything. I suppose it is all present in the Binding file but I can't find that in the repo as well. Could you help me with this?

**Comment by kl3jvi** [comment]
Hey @surajk16 ! Sorry for the delayed answer, I have build a library for this. Also I am using cpu info (c++ lib) to get cpu info
